#import "conf_problem.typ": *
#show: doc => conf(
  title: [
    Digital Systems: Problem Sheet 1
  ],
  authors: (
    (
      name: "Mark van der Wilk",
      role: "Lecturer & Adaptations"
    ),
    (
      name: "Mike Spivey",
      role: "Lecturer & Course Designer"
    ),
  ),
  include_outline: false,
  doc
)
#import "callouts.typ": *

#set par(first-line-indent: 1.5em, spacing: 0.65em)

#show raw.where(block: true): box.with(
  fill: luma(250),
  outset: (y: 3pt),
  radius: 2pt,
  stroke: luma(100),
  width: 1fr
)




_Questions on this sheet probe details of ARM Cortex-M0 assembly language,
and also of its encoding as binary machine code. It can't be emphasised
enough that, though a lot of this detail is needed for the experience of understanding how a particular computer works (which every Computer Science
student should enjoy at some stage), it isn't detail that is worth memorising in
the medium term. I.e., you need to understand and be able to reproduce the process and the logic, but you don't need to memorise the details._

#question[Find as many single Thumb instructions as you can that have the eﬀect
of setting register r0 to zero, and as many as you can that copy register r1
to register r0. In each case, the instruction may or may not set the condition
codes: say which.

_To answer this exercise, use the ARM Architecture Reference Manual (linked
from the `README`) to look up the details of some of the
instructions shown in red, orange, yellow or green in tables [A] and [B] of the
Rainbow Chart._]

#question[
The following listing shows a disassembly of the simple multiplication
routine from the lecture.
```
          func:
c0: 2200      movs    r0, #0
          loop:
c2: 2900      cmp     r1, #0
c4: d002      beq     cc <done>
c6: 3901      subs    r1, #1
c8: 1812      adds    r2, r2, r0
ca: e7fa      b       c2 <loop>
          done:
cc: 0010      movs    r0, r2
ce: 4770      bx      lr
```
(I have edited it a bit to remove distracting details.) Decode some of the instructions by hand, and in particular explain the displacements that appear
in the `beq` and `b` instructions.

_Again look up the instructions in the ARM Architecture Reference Manual,
and use the information about encodings given there to decypher some of the
hexadecimal numbers shown in the listing._
] <q:mul>

#question[
  I can run the disassembler on the final linked binary that is generated in lab1 by running the command
  ```sh
  arm-none-eabi-objdump -d func.elf
  ```
  See @lst:disassembly-func for part of the output I get. Using what you know about the startup sequence of the ARM chip, the memory map, and big/little endian encodings, explain why the values of the first 8 bytes are what they are. _To answer this question, you will need to run the disassembler yourself, and look at other parts of the result._
]

#question[
  Binary files in object (`.o`) or ELF (`.elf`) formats can contain a lot of additional information on top of just machine code. For example, in @lst:disassembly-func we see that the disassembler knows *1)* the file format, *2)* that there is a set of memory locations called `__vectors`, which is a name from `startup.c`, and *3)* later on in the disassembly, what the function names are.
  
  #set enum(numbering: "a)")
  + Is this additional information strictly necessary to run the program on the ARM chip?
  + The actual file we send to the micro:bit is `func.hex`, not `func.elf`. Try running the disassembler on `func.hex`. You get an error. Why do you think this is? Why do we choose to send a file with the information in `func.hex`, rather than a file like `func.elf`?
  + We can still run the disassembler on `func.hex`, but we need to supply some additional information through command line arguments. We can run:
    ```
  arm-none-eabi-objdump -m arm -M force-thumb -b ihex -D func.hex
  ```
    Run `arm-non-eabi-objdump --help` to find what these arguments do. Why do you need to add these?
  + @lst:disassembly-func-hex shows the beginning of the disassembly of `func.hex`. Do you recognise the first 8 bytes? The presentation is now different from the disassembly of `func.elf`. Why? Do the instructions that the listing shows make sense? Or, equivalently, will those instructions ever get executed?
]

#figure([
  ```
markvdw@daedalus-2 lab1-asm % arm-none-eabi-objdump -d func.elf | head -n 10

func.elf:     file format elf32-littlearm


Disassembly of section .text:

00000000 <__vectors>:
   0:	00 40 00 20 dd 06 00 00 b3 07 00 00 b3 07 00 00     .@. ............
	...
  2c:	b3 07 00 00 00 00 00 00 00 00 00 00 b3 07 00 00     ................
  ```
], caption: [First few lines of the disassembly of the binary file generated by lab 1. Note the use of "piping". The output of the first command is passed into the next command `head -n 10`, which displays only the first 10 lines. This is quite useful in shell scripting.]) <lst:disassembly-func>

#figure([
```
markvdw@daedalus-2 lab1-asm % arm-none-eabi-objdump -m arm -M force-thumb -b ihex -D func.hex | head -n20

func.hex:     file format ihex


Disassembly of section .sec1:

00000000 <.sec1>:
   0:	4000      	ands	r0, r0
   2:	2000      	movs	r0, #0
   4:	06dd      	lsls	r5, r3, #27
   6:	0000      	movs	r0, r0
   8:	07b3      	lsls	r3, r6, #30
   a:	0000      	movs	r0, r0
   c:	07b3      	lsls	r3, r6, #30
	...
  2a:	0000      	movs	r0, r0
  2c:	07b3      	lsls	r3, r6, #30
	...
  36:	0000      	movs	r0, r0
  38:	07b3      	lsls	r3, r6, #30
```], caption: [Disassembly of `func.hex`.]) <lst:disassembly-func-hex>


#question[
  As it stands, the multiplication routine shown in @q:mul has a loop that contains 5 instructions, and takes 7 cycles for each iteration but the last: three cycles for the branch back to the start, and one cycle for each of the other instructions, including the untaken conditional branch. Try to rewrite the loop so that it contains fewer instructions. _A good solution has 3 instructions in the loop, taking 5 cycles per iteration, but it is possible to go further using 'loop unrolling' and make a still faster routine._
]

#question[
  Note that conditional branch instructions in Thumb code, such as `beq`, have a displacement field of limited size, but the unconditional branch `b` has a bigger displacement field. Show how a two-instruction sequence can be used to simulate conditional branches with a bigger range than can be achieved with a single `beq`. What is the penalty in execution time for doing this? The branch-and-link instruction `bl` has a still larger displacement field. Can it be used in a similar way to simulate even longer conditional branches?
]

#question[
  Show with examples why diﬀerent instructions `blt` and `blo` are needed following comparison of signed and unsigned numbers. Find out the conditions under which each of these branches is taken, and explain why the result is correct in each case.
]

#question[
  Write in C a routine for unsigned integer division, using the naïve algorithm based on repeated subtraction. Code the result in assembly language. To answer this problem well, you must: formulate precisely the problem to be solved; give a clear algorithm for the problem and justify its correctness; code the algorithm in commented assembly language in an eﬃcient way, considering the possibility of overflow; comment on errors that should be detected.
]

#question[
  Repeat the previous exercise using a better algorithm. Fancier versions of the ARM have an instruction `clz r1, r2` that sets `r1` to the number of leading zeroes in the binary number in `r2`; what use is this instruction in writing a division routine?
]

#pagebreak()

#answer[]

#answer[]

#answer[
  From lectures, we know that the first 32-bit number will be loaded into the Stack Pointer register `sp`, and the second 32-bit number into the Program Counter `pc`. 
  
  The stack is the machanism that we use to store local variables in functions, and in later lectures we learn that `sp` is initialised to the highest memory address in RAM. From the memory map that we saw in lectures, we know that this address is `0x20004000`. In `.hex` files, numbers are stored in the "little-endian" format, which means that the end of the number (least significant bytes) are stored at the end of the sequence. This is why the number is displayed as `00 40 00 20`, keeping in mind that a byte consists of two hexadecimal numbers.

  The second word number will be sent to the program counter. This effectively executes a branch instruction, jumping into a new subroutine. To find out which function we jump into, we need to find the function located at the address indicated by `dd 06 00 00`, which (translating from little-endian) is the value `0x000006dd` (this may be different when you compile). We firstly note something odd about this number. It's an odd number (`0xd = 13`)! An instruction cannot be at this location, since instructions are two bytes long, and are stored one after the other. In my disassembly (see @lst:disassembly-func-later), we find the function `__reset` at address `0x06dc`, and this _is_ where the CPU jumps to. What explains this difference? It is the convention that when the CPU jumps to an odd address, that it switches to executing the 16-bit Thumb instructions, rather than the 32-bit native ARM instructions (as discussed in lectures). The Cortex-M0 can only execute these Thumb instructions, but we still need to follow this convention for compatibility with larger ARM chips.

  The selection of `__reset` as the first function that the CPU jumps to, is done by placing the address of the function in the 2nd field of the `__vectors` array in `startup.c`.
]

  #figure([
  ```
000006ca <memset>:
 6ca:	2a00      	cmp	r2, #0
 6cc:	d005      	beq.n	6da <memset+0x10>
 6ce:	0003      	movs	r3, r0
 6d0:	1812      	adds	r2, r2, r0
 6d2:	7019      	strb	r1, [r3, #0]
 6d4:	3301      	adds	r3, #1
 6d6:	4293      	cmp	r3, r2
 6d8:	d1fb      	bne.n	6d2 <memset+0x8>
 6da:	4770      	bx	lr

000006dc <__reset>:
 6dc:	b570      	push	{r4, r5, r6, lr}
 6de:	4b0e      	ldr	r3, [pc, #56]	@ (718 <__reset+0x3c>)
 6e0:	2200      	movs	r2, #0
 6e2:	601a      	str	r2, [r3, #0]
 6e4:	3b01      	subs	r3, #1
```], caption: [Later disassembly of `func.elf`, generated by lab 1.], placement: none) <lst:disassembly-func-later>

#answer[
#set enum(numbering: "a)")
+ No, function names are not needed to run the code. These are useful to _humans_, and are used in C code to make it easy for _humans_ to remember what re-usable pieces of code (i.e. subroutines) are for. When the compiler produces byte code, these subroutines are given an address in memory, and this is all that an branch instruction needs to jump to a new subroutine.
+ The `arm-none-eabi-objcopy` program will remove this unnecessary information, and just leave the instructions. This will ultimately determine the exact sequence of binary that is written to the Flash memory on the micro:bit. This is good, so we don't waste valuable program space (we only have 256KB!) on data that only matters to humans, and not to running the acutal program. However, it does mean, that the `.hex` file is lacking the helpful information that is displayed in the disassembler. In fact, when the disassembler is presented with just a sequence of hexadecimal numbers, it doesn't even know how to interpet it! It could be Native ARM code, where the instructions are all 32 bits long, or Thumb code, where they are 16 bits long! The byte code could be interpreted in both ways, and both sequences of instructions can be run... Although only one will run according to the intentions of the original programmer. However, since the assembler is faced with two possible interpretations of the machine code, and it has no way of knowing what hte intentions of the original programmer were, it cannot determine how to proceed, and we get an error.
+ RTFM (Read the Fantastic Manual)
+ The first 8 bytes still encode the highest memory address in RAM, followed by the address of the `__reset` function that should be run on startup. However, we now see this data displayed not just as a sequence of numbers as before, but instead interpreted as instructions. This is because the information that this `.vectors` section is just binary data is _not_ stored in the `.hex` file, and the disassembler just chooses to interpret this as instructions. It is up to _us_ as engineers (or... reverse-engineers) to know that the ARM CPU interprets these numbers _not_ as instructions, but instead as values for the Stack Pointer and Program Counter. So the instructions that are displayed are the correct decodings of the machine code, but they will never be executed as instructions. And so I would say that they don't "make sense".
]
